[package]
name = "theblackrose-backend"
version = "0.1.0"
authors = ["Darragh Van Tichelen <info@darragh.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.11.0-beta.1"
actix-cors = { git = "https://github.com/andy128k/actix-extras", branch="update-dependencies" }
actix-files = "0.6.0-beta.1"
actix-web = "4.0.0-beta.1"
actix-web-httpauth = { git = "https://github.com/andy128k/actix-extras", branch="update-dependencies" }
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
derive_more = "0.99.11"
diesel = { version = "1.4.5", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.8.2"
jsonwebtoken = "7.2.0"
log = "0.4.14"
r2d2 = "0.8.9"
reqwest = "0.11.0"
riven = "1.11.1"
serde = "1.0.123"
serde_json = "1.0.61"
strum = "0.20.0"
strum_macros = "0.20.1"
tokio = { version = "1.1.0", features = ["full"] }
