[package]
name = "theblackrose-backend"
version = "0.1.0"
authors = ["Darragh Van Tichelen <info@darragh.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-cors = "0.5.1"
actix-web = "3.2.0"
actix-web-httpauth = "0.5.0"
base64 = "0.13.0"
chrono = {version="0.4.19", features=["serde"]}
derive_more = "0.99.11"
diesel = { version = "1.4.5", features= ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
r2d2 = "0.8.9"
reqwest = "0.10.8"
riven = "1.10.2"
serde = "1.0.117"
serde_json = "1.0.59"
tokio = { version = "0.2", features = ["full"] }
